find TLE for given cartesian state vector using Nelder-Mead optimization
nsat/sgp4-rs pull request #28
Opened 2023-07-11 16:29 UTC by spire-josh-singer

Idea is to transform specific cartesian state vector to a TLE such that if SGP4 is initialized with those parameters, it would produce the state vector if propagated to that epoch.

the method is

- transform the cartesian state vector to purely keplerian orbit parameters
- Use these as a starting point for an optimization method:
- https://en.wikipedia.org/wiki/Nelder%E2%80%93Mead_method

We vary all 6 orbital parameters in the TLE. The objective function runs SGP4 and figures out the sum of squares error in the position and velocity vectors.

2023-07-17 08:23 UTC, elliemcc-spire requested changes
Looking good - just a small clippy warning for vec

2023-07-17 08:23 UTC, elliemcc-spire commented on src/tlegen.rs
> +        let perturbations = vec![0.1, 0.1, 0.01, 1.0, 5.0, 1.0];
Little clippy warning here for vec

2023-07-19 11:03 UTC, elliemcc-spire approved these changes
LGTM

2023-07-19 12:27 UTC, spire-josh-singer commented on src/tlegen.rs
> +        let perturbations = vec![0.1, 0.1, 0.01, 1.0, 5.0, 1.0];
fixed

2023-07-19 12:28 UTC, merged